from langchain.schema import Document

test_response = res = {
    "query": "Health benefits of green tea",
    "result": "Green tea has been found to have several health benefits. According to studies, drinking green tea can reduce the risk of developing complaints that limit the ability to function independently in elderly individuals. It has also been shown to reduce the chance of fatal pneumonia, psychological stress, and depression. Green tea consumption has been associated with longer lifespan and a reduced chance of some form of disability. Additionally, research on lab mice has shown that replacing drinking water with green tea can lead to a longer lifespan and potentially help repair defects in the immune system. However, the exact mechanisms behind these benefits are not fully understood and further clinical trials are needed to confirm the protective effects of green tea.",
    "source_documents": [
        Document(
            page_content="Grow old healthily with green tea\nThe more cups of green tea over-65s drink each day, the healthier they are likely to be. According to an epidemiological study from Tohuku University, each cup of green tea a day that elderly people drink reduces the chance of them developing complaints that limit their ability to function independently.\nStudy\nThe researchers followed a group of men and women in the town of Ohsaki, all of whom were 65 or older in 2006. They were looking for factors that reduce old people's likelihood of needing medical attention. According to the study, green tea is one of these factors.\nResults\nThe Japanese discovered that while green tea does not offer protection against prostate cancer [Br J Cancer. 2006 Aug 7; 95(3): 371-3.], it does reduce the chance of fatal pneumonia \n[Am J Clin Nutr. 2009 Sep; 90(3): 672-9.], psychological stress [Am J Clin Nutr. 2009 Nov; 90(5): 1390-6.] and of depression [Am J Clin Nutr. 2009 Dec; 90(6): 1615-22.].\nIt's hardly surprising that the green-tea drinkers lived longer than the non-tea drinkers in the study. [JAMA. 2006 Sep 13; 296(10): 1255-65.]\nThe Japanese have published the results of another study, in the American Journal of Clinical Nutrition, based on the data in the Ohsaki Cohort 2006 Study. This time they monitored 14,000 participants for a period of three years, and looked at whether green-tea drinkers developed complaints which made them require help less frequently. In the words of the study: the researchers looked at the relationship between drinking green tea and 'incident functional disability'.\nAs you can see, drinking five or more cups of green tea per day reduces the chance of some form of invalidity by almost 35 percent.\nConclusion\n\"Green tea consumption is inversely associated with incident functional disability\", the researchers conclude. \"Clinical trials are necessary to confirm the protective effect of green tea against functional disability.\"\nSource:\nAm J Clin Nutr. 2012 Mar;95(3):732-9.\n",
            metadata={
                "archive_link": "https://www.ergo-log.com/archives2019a.html#131",
                "article_date": "22.03.2019",
                "article_link": "https://www.ergo-log.com/healthilywithgreentea.html",
                "article_title": "The more cups of green tea over-65s drink each day, the healthier they are likely to be. According to an epidemiological study from Tohuku University, each cup of green tea a day that elderly people drink reduces the chance of them developing complaints that limit their ability to function independently.",
            },
        ),
        Document(
            page_content="Grow old healthily with green tea\nThe more cups of green tea over-65s drink each day, the healthier they are likely to be. According to an epidemiological study from Tohuku University, each cup of green tea a day that elderly people drink reduces the chance of them developing complaints that limit their ability to function independently.\nStudy\nThe researchers followed a group of men and women in the town of Ohsaki, all of whom were 65 or older in 2006. They were looking for factors that reduce old people's likelihood of needing medical attention. According to the study, green tea is one of these factors.\nResults\nThe Japanese discovered that while green tea does not offer protection against prostate cancer [Br J Cancer. 2006 Aug 7; 95(3): 371-3.], it does reduce the chance of fatal pneumonia \n[Am J Clin Nutr. 2009 Sep; 90(3): 672-9.], psychological stress [Am J Clin Nutr. 2009 Nov; 90(5): 1390-6.] and of depression [Am J Clin Nutr. 2009 Dec; 90(6): 1615-22.].\nIt's hardly surprising that the green-tea drinkers lived longer than the non-tea drinkers in the study. [JAMA. 2006 Sep 13; 296(10): 1255-65.]\nThe Japanese have published the results of another study, in the American Journal of Clinical Nutrition, based on the data in the Ohsaki Cohort 2006 Study. This time they monitored 14,000 participants for a period of three years, and looked at whether green-tea drinkers developed complaints which made them require help less frequently. In the words of the study: the researchers looked at the relationship between drinking green tea and 'incident functional disability'.\nAs you can see, drinking five or more cups of green tea per day reduces the chance of some form of invalidity by almost 35 percent.\nConclusion\n\"Green tea consumption is inversely associated with incident functional disability\", the researchers conclude. \"Clinical trials are necessary to confirm the protective effect of green tea against functional disability.\"\nSource:\nAm J Clin Nutr. 2012 Mar;95(3):732-9.\n",
            metadata={
                "archive_link": "https://www.ergo-log.com/archives2019a.html#131",
                "article_date": "22.03.2019",
                "article_link": "https://www.ergo-log.com/healthilywithgreentea.html",
                "article_title": "The more cups of green tea over-65s drink each day, the healthier they are likely to be. According to an epidemiological study from Tohuku University, each cup of green tea a day that elderly people drink reduces the chance of them developing complaints that limit their ability to function independently.",
            },
        ),
        Document(
            page_content="Drink green tea instead of water \x96 and live longer\nIf you replace lab mice's drinking water with green tea, they live longer. Researchers at the Japanese National Institute for Longevity Sciences discovered this when they did experiments on male C57BL/6 mice. This type of lab mouse often develops cancer of the lymph glands in old age, and like many other rodents is also susceptible to kidney problems.\nStudy\nThe researchers used a standard green tea extract often found in supplements. It's called Sunphenon and is manufactured by Taiyo Kagaku. \"It was composed mainly of (-)-epigallocatechin 3-O-gallate (18.0%), (-)-gallocatechin 3-O-gallate (11.6%), (-)-epicatechin 3-O-gallate (4.6%), (-)-epigallocatechin (15.0%), (+)-gallocatechin (14.8%), (-)-epicatechin (7.0%), and (+)-catechin (3.5%)\", the researchers write. They mixed 80 mg in one litre of water and gave it to their mice.\nAdministration started when the animals were 13 months old. A control group was given ordinary drinking water.\nResults\nThe figure below shows that the maximum lifespan of the mice that drank green tea is 6 percent longer than that of the mice that drank water. The effect is not particularly remarkable. What is more interesting is the reduction in mortality between 20 and 30 months of age.\nHumans who have just entered the second half of their life are more likely to die of cancer. One theory is that the immune system starts to work less well, so it doesn't remove all cancer cells. The researchers speculate that the polyphenols in green tea may help repair this defect.\nThe green tea extract had no effect on the mice's weight. In the early days of longevity research, life-extending effects were incorrectly ascribed to because they reduced the subjects' food intake. As a result the animals lived longer. This was not the case in this experiment.\nMechanism\nThe researchers admit that they don't know exactly how green tea works. They say that it's more important that they have established that green tea does work: \"Even if the basic mechanism is not fully elucidated, the confirmation of the present study may provide a rational approach for the nutritional interventions in aging and age-associated disorders in humans.\"\nSource:\nBiogerontology. 2007 Oct; 8(5): 567-73.\n",
            metadata={
                "archive_link": "https://www.ergo-log.com/archives2015a.html#83",
                "article_date": "30.03.2015",
                "article_link": "https://www.ergo-log.com/drinkgreentea.html",
                "article_title": "If you replace lab mice's drinking water with green tea, they live longer. Researchers at the Japanese National Institute for Longevity Sciences discovered this when they did experiments on male C57BL/6 mice. This type of lab mouse often develops cancer of the lymph glands in old age, and like many other rodents is also susceptible to kidney problems.",
            },
        ),
        Document(
            page_content="Drink green tea instead of water \x96 and live longer\nIf you replace lab mice's drinking water with green tea, they live longer. Researchers at the Japanese National Institute for Longevity Sciences discovered this when they did experiments on male C57BL/6 mice. This type of lab mouse often develops cancer of the lymph glands in old age, and like many other rodents is also susceptible to kidney problems.\nStudy\nThe researchers used a standard green tea extract often found in supplements. It's called Sunphenon and is manufactured by Taiyo Kagaku. \"It was composed mainly of (-)-epigallocatechin 3-O-gallate (18.0%), (-)-gallocatechin 3-O-gallate (11.6%), (-)-epicatechin 3-O-gallate (4.6%), (-)-epigallocatechin (15.0%), (+)-gallocatechin (14.8%), (-)-epicatechin (7.0%), and (+)-catechin (3.5%)\", the researchers write. They mixed 80 mg in one litre of water and gave it to their mice.\nAdministration started when the animals were 13 months old. A control group was given ordinary drinking water.\nResults\nThe figure below shows that the maximum lifespan of the mice that drank green tea is 6 percent longer than that of the mice that drank water. The effect is not particularly remarkable. What is more interesting is the reduction in mortality between 20 and 30 months of age.\nHumans who have just entered the second half of their life are more likely to die of cancer. One theory is that the immune system starts to work less well, so it doesn't remove all cancer cells. The researchers speculate that the polyphenols in green tea may help repair this defect.\nThe green tea extract had no effect on the mice's weight. In the early days of longevity research, life-extending effects were incorrectly ascribed to because they reduced the subjects' food intake. As a result the animals lived longer. This was not the case in this experiment.\nMechanism\nThe researchers admit that they don't know exactly how green tea works. They say that it's more important that they have established that green tea does work: \"Even if the basic mechanism is not fully elucidated, the confirmation of the present study may provide a rational approach for the nutritional interventions in aging and age-associated disorders in humans.\"\nSource:\nBiogerontology. 2007 Oct; 8(5): 567-73.\n",
            metadata={
                "archive_link": "https://www.ergo-log.com/archives2015a.html#83",
                "article_date": "30.03.2015",
                "article_link": "https://www.ergo-log.com/drinkgreentea.html",
                "article_title": "If you replace lab mice's drinking water with green tea, they live longer. Researchers at the Japanese National Institute for Longevity Sciences discovered this when they did experiments on male C57BL/6 mice. This type of lab mouse often develops cancer of the lymph glands in old age, and like many other rodents is also susceptible to kidney problems.",
            },
        ),
    ],
}
